# Generated by Django 5.1.1 on 2024-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_email', models.CharField(max_length=100)),
                ('pass1', models.CharField(default='', max_length=10)),
                ('pass2', models.CharField(default='', max_length=10)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=7000)),
                ('college_name', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
