# Generated by Django 5.1.1 on 2024-09-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='candidate_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='candidate_name',
            new_name='student_name',
        ),
    ]
