# Generated by Django 5.1.1 on 2024-09-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_candidate_email_student_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
