# Generated by Django 5.1.1 on 2024-09-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('pass1', models.CharField(default='', max_length=10)),
                ('pass2', models.CharField(default='', max_length=10)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=7000)),
                ('college_name', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=2)),
            ],
        ),
    ]
