# Generated by Django 5.1.1 on 2024-09-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
