# Generated by Django 5.1.1 on 2024-09-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='pass2',
        ),
    ]
